[package]
name = "rtftp"
version = "0.1.0"
authors = ["Reiner Herrmann <reiner@reiner-h.de>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
nix = "0.13.0"

[[bin]]
name = "rtftpd"
path = "src/tftpd.rs"
